ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS summary_polyline TEXT,
  ADD COLUMN IF NOT EXISTS splits JSONB,
  ADD COLUMN IF NOT EXISTS best_efforts JSONB,
  ADD COLUMN IF NOT EXISTS avg_cadence NUMERIC,
  ADD COLUMN IF NOT EXISTS avg_watts NUMERIC,
  ADD COLUMN IF NOT EXISTS elapsed_time INT,
  ADD COLUMN IF NOT EXISTS max_speed NUMERIC;
